name: Workflow Run
on:
  workflow_run:
    workflows:
      - PR Open
    types: completed
jobs:
  comment:
    runs-on: ubuntu-latest
    environment:
      name: testytest
    steps:
      - run: echo '${{ toJSON(github) }}'
      - run: >
          number=$(curl -s ${{ github.event.workflow_run.jobs_url }} |
            jq -r '.jobs[0].steps[] | select(.name | contains("number.txt")) | .name' |
            cut -f 3 -d ' ')
          echo "PR: #$number"
