name: Manual Dispatch
on:
  workflow_dispatch:
    inputs:
      foo:
        description: Foo
        type: number

jobs:
  dispatch:
    name: Do Dispatchy Things
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: console.log(context.payload.inputs);
