name: Manual Dispatch
on: workflow_dispatch

jobs:
  delete-env:
    name: Delete Environment
    runs-on: ubuntu-latest
    steps:
      - name: Generate JWT
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Delete environment
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          ENVIRONMENT: testytest
        run: |
          gh api -X DELETE repos/${{ github.repository }}/environments/$ENVIRONMENT
