name: PR Open
on:
  pull_request:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          echo ${{ github.sha }}
          echo $GITHUB_SHA
          echo ${{ toJSON(github.event.pull_request) }}
      - run: echo ${{ github.event.pull_request.number }} > number.txt
