name: PR Open
on:
  pull_request:
    branches: main
permissions:
  actions: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Dispatch
        env: 
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api repos/{owner}/{repo}/actions/workflows/dispatched.yml/dispatches \
            -f ref=${{ github.ref }} -f 'inputs[issue]=${{ github.event.number }}'
