name: Push
on: push
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Test
				run: echo test
  two:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        broken:
    steps:
      - name: Output
				run: echo ${{ matrix.broken }}
