name: Healthcheck
on: push
jobs:
  script:
    name: Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        id: runscript
        uses: actions/github-script@v6
        with:
          script: require('.github/scripts/test')(core);
      - name: Output steps
        run: |
          echo '${{ github.job }}'
          echo ${{ github.workflow_sha }}
          gh workflow view ${{ github.workflow }} -r ${{ github.ref}} -y | yq eval .jobs.${{ github.job }}.name -
