name: Healthcheck
on: push
jobs:
  script:
    name: Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        id: runscript
        uses: actions/github-script@v6
        with:
          script: require('.github/scripts/test')(core);
      - name: Output steps
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo '${{ github.job }}'
          echo ${{ github.workflow }}
          JOB_NAME=$(gh workflow view ${{ github.workflow }} -r ${{ github.ref}} -y | yq eval .jobs.${{ github.job }}.name -)
          gh run view ${{ github.run_id }} --json jobs --jq ".jobs[] | select(.name == \"$JOB_NAME\") | .url, (.steps[] | select(.name == \"Run script\") | \"?pr=1&check_suite_focus#step:\(.number):1\")"
