name: Healthcheck
on: push
jobs:
  script:
    name: Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        id: runscript
        uses: actions/github-script@v6
        with:
          script: require('.github/scripts/test')(core);
      - name: Output steps
        run: echo '${{ toJSON(steps.runscript) }}'
